export const COUNTRIES = [
    { name: 'Afghanistan', iso: 'AF', code: '+93', flag: '🇦🇫' },
    { name: 'Albania', iso: 'AL', code: '+355', flag: '🇦🇱' },
    { name: 'Algeria', iso: 'DZ', code: '+213', flag: '🇩🇿' },
    { name: 'Andorra', iso: 'AD', code: '+376', flag: '🇦🇩' },
    { name: 'Angola', iso: 'AO', code: '+244', flag: '🇦🇴' },
    { name: 'Argentina', iso: 'AR', code: '+54', flag: '🇦🇷' },
    { name: 'Armenia', iso: 'AM', code: '+374', flag: '🇦🇲' },
    { name: 'Australia', iso: 'AU', code: '+61', flag: '🇦🇺' },
    { name: 'Austria', iso: 'AT', code: '+43', flag: '🇦🇹' },
    { name: 'Azerbaijan', iso: 'AZ', code: '+994', flag: '🇦🇿' },
    { name: 'Bahamas', iso: 'BS', code: '+1', flag: '🇧🇸' },
    { name: 'Bahrain', iso: 'BH', code: '+973', flag: '🇧🇭' },
    { name: 'Bangladesh', iso: 'BD', code: '+880', flag: '🇧🇩' },
    { name: 'Barbados', iso: 'BB', code: '+1', flag: '🇧🇧' },
    { name: 'Belarus', iso: 'BY', code: '+375', flag: '🇧🇾' },
    { name: 'Belgium', iso: 'BE', code: '+32', flag: '🇧🇪' },
    { name: 'Belize', iso: 'BZ', code: '+501', flag: '🇧🇿' },
    { name: 'Benin', iso: 'BJ', code: '+229', flag: '🇧🇯' },
    { name: 'Bhutan', iso: 'BT', code: '+975', flag: '🇧🇹' },
    { name: 'Bolivia', iso: 'BO', code: '+591', flag: '🇧🇴' },
    { name: 'Bosnia and Herzegovina', iso: 'BA', code: '+387', flag: '🇧🇦' },
    { name: 'Botswana', iso: 'BW', code: '+267', flag: '🇧🇼' },
    { name: 'Brazil', iso: 'BR', code: '+55', flag: '🇧🇷' },
    { name: 'Brunei', iso: 'BN', code: '+673', flag: '🇧🇳' },
    { name: 'Bulgaria', iso: 'BG', code: '+359', flag: '🇧🇬' },
    { name: 'Burundi', iso: 'BI', code: '+257', flag: '🇧🇮' },
    { name: 'Cambodia', iso: 'KH', code: '+855', flag: '🇰🇭' },
    { name: 'Cameroon', iso: 'CM', code: '+237', flag: '🇨🇲' },
    { name: 'Canada', iso: 'CA', code: '+1', flag: '🇨🇦' },
    { name: 'Cape Verde', iso: 'CV', code: '+238', flag: '🇨🇻' },
    { name: 'Chad', iso: 'TD', code: '+235', flag: '🇹🇩' },
    { name: 'Chile', iso: 'CL', code: '+56', flag: '🇨🇱' },
    { name: 'China', iso: 'CN', code: '+86', flag: '🇨🇳' },
    { name: 'Colombia', iso: 'CO', code: '+57', flag: '🇨🇴' },
    { name: 'Comoros', iso: 'KM', code: '+269', flag: '🇰🇲' },
    { name: 'Costa Rica', iso: 'CR', code: '+506', flag: '🇨🇷' },
    { name: 'Croatia', iso: 'HR', code: '+385', flag: '🇭🇷' },
    { name: 'Cuba', iso: 'CU', code: '+53', flag: '🇨🇺' },
    { name: 'Cyprus', iso: 'CY', code: '+357', flag: '🇨🇾' },
    { name: 'Czech Republic', iso: 'CZ', code: '+420', flag: '🇨🇿' },
    { name: 'Denmark', iso: 'DK', code: '+45', flag: '🇩🇰' },
    { name: 'Djibouti', iso: 'DJ', code: '+253', flag: '🇩🇯' },
    { name: 'Dominica', iso: 'DM', code: '+1', flag: '🇩🇲' },
    { name: 'Dominican Republic', iso: 'DO', code: '+1', flag: '🇩🇴' },
    { name: 'Ecuador', iso: 'EC', code: '+593', flag: '🇪🇨' },
    { name: 'Egypt', iso: 'EG', code: '+20', flag: '🇪🇬' },
    { name: 'El Salvador', iso: 'SV', code: '+503', flag: '🇸🇻' },
    { name: 'Eritrea', iso: 'ER', code: '+291', flag: '🇪🇷' },
    { name: 'Estonia', iso: 'EE', code: '+372', flag: '🇪🇪' },
    { name: 'Eswatini', iso: 'SZ', code: '+268', flag: '🇸🇿' },
    { name: 'Ethiopia', iso: 'ET', code: '+251', flag: '🇪🇹' },
    { name: 'Fiji', iso: 'FJ', code: '+679', flag: '🇫🇯' },
    { name: 'Finland', iso: 'FI', code: '+358', flag: '🇫🇮' },
    { name: 'France', iso: 'FR', code: '+33', flag: '🇫🇷' },
    { name: 'Gabon', iso: 'GA', code: '+241', flag: '🇬🇦' },
    { name: 'Gambia', iso: 'GM', code: '+220', flag: '🇬🇲' },
    { name: 'Georgia', iso: 'GE', code: '+995', flag: '🇬🇪' },
    { name: 'Germany', iso: 'DE', code: '+49', flag: '🇩🇪' },
    { name: 'Ghana', iso: 'GH', code: '+233', flag: '🇬🇭' },
    { name: 'Greece', iso: 'GR', code: '+30', flag: '🇬🇷' },
    { name: 'Grenada', iso: 'GD', code: '+1', flag: '🇬🇩' },
    { name: 'Guatemala', iso: 'GT', code: '+502', flag: '🇬🇹' },
    { name: 'Guinea', iso: 'GN', code: '+224', flag: '🇬🇳' },
    { name: 'Guyana', iso: 'GY', code: '+592', flag: '🇬🇾' },
    { name: 'Haiti', iso: 'HT', code: '+509', flag: '🇭🇹' },
    { name: 'Honduras', iso: 'HN', code: '+504', flag: '🇭🇳' },
    { name: 'Hungary', iso: 'HU', code: '+36', flag: '🇭🇺' },
    { name: 'Iceland', iso: 'IS', code: '+354', flag: '🇮🇸' },
    { name: 'India', iso: 'IN', code: '+91', flag: '🇮🇳' },
    { name: 'Indonesia', iso: 'ID', code: '+62', flag: '🇮🇩' },
    { name: 'Iran', iso: 'IR', code: '+98', flag: '🇮🇷' },
    { name: 'Iraq', iso: 'IQ', code: '+964', flag: '🇮🇶' },
    { name: 'Ireland', iso: 'IE', code: '+353', flag: '🇮🇪' },
    { name: 'Israel', iso: 'IL', code: '+972', flag: '🇮🇱' },
    { name: 'Italy', iso: 'IT', code: '+39', flag: '🇮🇹' },
    { name: 'Jamaica', iso: 'JM', code: '+1', flag: '🇯🇲' },
    { name: 'Japan', iso: 'JP', code: '+81', flag: '🇯🇵' },
    { name: 'Jordan', iso: 'JO', code: '+962', flag: '🇯🇴' },
    { name: 'Kazakhstan', iso: 'KZ', code: '+7', flag: '🇰🇿' },
    { name: 'Kenya', iso: 'KE', code: '+254', flag: '🇰🇪' },
    { name: 'Kiribati', iso: 'KI', code: '+686', flag: '🇰🇮' },
    { name: 'Kuwait', iso: 'KW', code: '+965', flag: '🇰🇼' },
    { name: 'Kyrgyzstan', iso: 'KG', code: '+996', flag: '🇰🇬' },
    { name: 'Laos', iso: 'LA', code: '+856', flag: '🇱🇦' },
    { name: 'Latvia', iso: 'LV', code: '+371', flag: '🇱🇻' },
    { name: 'Lebanon', iso: 'LB', code: '+961', flag: '🇱🇧' },
    { name: 'Lesotho', iso: 'LS', code: '+266', flag: '🇱🇸' },
    { name: 'Liberia', iso: 'LR', code: '+231', flag: '🇱🇷' },
    { name: 'Libya', iso: 'LY', code: '+218', flag: '🇱🇾' },
    { name: 'Liechtenstein', iso: 'LI', code: '+423', flag: '🇱🇮' },
    { name: 'Lithuania', iso: 'LT', code: '+370', flag: '🇱🇹' },
    { name: 'Luxembourg', iso: 'LU', code: '+352', flag: '🇱🇺' },
    { name: 'Madagascar', iso: 'MG', code: '+261', flag: '🇲🇬' },
    { name: 'Malawi', iso: 'MW', code: '+265', flag: '🇲🇼' },
    { name: 'Malaysia', iso: 'MY', code: '+60', flag: '🇲🇾' },
    { name: 'Maldives', iso: 'MV', code: '+960', flag: '🇲🇻' },
    { name: 'Mali', iso: 'ML', code: '+223', flag: '🇲🇱' },
    { name: 'Malta', iso: 'MT', code: '+356', flag: '🇲🇹' },
    { name: 'Mexico', iso: 'MX', code: '+52', flag: '🇲🇽' },
    { name: 'Moldova', iso: 'MD', code: '+373', flag: '🇲🇩' },
    { name: 'Monaco', iso: 'MC', code: '+377', flag: '🇲🇨' },
    { name: 'Mongolia', iso: 'MN', code: '+976', flag: '🇲🇳' },
    { name: 'Montenegro', iso: 'ME', code: '+382', flag: '🇲🇪' },
    { name: 'Morocco', iso: 'MA', code: '+212', flag: '🇲🇦' },
    { name: 'Mozambique', iso: 'MZ', code: '+258', flag: '🇲🇿' },
    { name: 'Myanmar', iso: 'MM', code: '+95', flag: '🇲🇲' },
    { name: 'Namibia', iso: 'NA', code: '+264', flag: '🇳🇦' },
    { name: 'Nauru', iso: 'NR', code: '+674', flag: '🇳🇷' },
    { name: 'Nepal', iso: 'NP', code: '+977', flag: '🇳🇵' },
    { name: 'Netherlands', iso: 'NL', code: '+31', flag: '🇳🇱' },
    { name: 'New Zealand', iso: 'NZ', code: '+64', flag: '🇳🇿' },
    { name: 'Nicaragua', iso: 'NI', code: '+505', flag: '🇳🇮' },
    { name: 'Niger', iso: 'NE', code: '+227', flag: '🇳🇪' },
    { name: 'Nigeria', iso: 'NG', code: '+234', flag: '🇳🇬' },
    { name: 'North Korea', iso: 'KP', code: '+850', flag: '🇰🇵' },
    { name: 'Norway', iso: 'NO', code: '+47', flag: '🇳🇴' },
    { name: 'Oman', iso: 'OM', code: '+968', flag: '🇴🇲' },
    { name: 'Pakistan', iso: 'PK', code: '+92', flag: '🇵🇰' },
    { name: 'Panama', iso: 'PA', code: '+507', flag: '🇵🇦' },
    { name: 'Papua New Guinea', iso: 'PG', code: '+675', flag: '🇵🇬' },
    { name: 'Paraguay', iso: 'PY', code: '+595', flag: '🇵🇾' },
    { name: 'Peru', iso: 'PE', code: '+51', flag: '🇵🇪' },
    { name: 'Philippines', iso: 'PH', code: '+63', flag: '🇵🇭' },
    { name: 'Poland', iso: 'PL', code: '+48', flag: '🇵🇱' },
    { name: 'Portugal', iso: 'PT', code: '+351', flag: '🇵🇹' },
    { name: 'Qatar', iso: 'QA', code: '+974', flag: '🇶🇦' },
    { name: 'Romania', iso: 'RO', code: '+40', flag: '🇷🇴' },
    { name: 'Russia', iso: 'RU', code: '+7', flag: '🇷🇺' },
    { name: 'Rwanda', iso: 'RW', code: '+250', flag: '🇷🇼' },
    { name: 'Saint Kitts and Nevis', iso: 'KN', code: '+1', flag: '🇰🇳' },
    { name: 'Saint Lucia', iso: 'LC', code: '+1', flag: '🇱🇨' },
    { name: 'Saint Vincent and the Grenadines', iso: 'VC', code: '+1', flag: '🇻🇨' },
    { name: 'Samoa', iso: 'WS', code: '+685', flag: '🇼🇸' },
    { name: 'San Marino', iso: 'SM', code: '+378', flag: '🇸🇲' },
    { name: 'Saudi Arabia', iso: 'SA', code: '+966', flag: '🇸🇦' },
    { name: 'Senegal', iso: 'SN', code: '+221', flag: '🇸🇳' },
    { name: 'Serbia', iso: 'RS', code: '+381', flag: '🇷🇸' },
    { name: 'Seychelles', iso: 'SC', code: '+248', flag: '🇸🇨' },
    { name: 'Sierra Leone', iso: 'SL', code: '+232', flag: '🇸🇱' },
    { name: 'Singapore', iso: 'SG', code: '+65', flag: '🇸🇬' },
    { name: 'Slovakia', iso: 'SK', code: '+421', flag: '🇸🇰' },
    { name: 'Slovenia', iso: 'SI', code: '+386', flag: '🇸🇮' },
    { name: 'Somalia', iso: 'SO', code: '+252', flag: '🇸🇴' },
    { name: 'South Africa', iso: 'ZA', code: '+27', flag: '🇿🇦' },
    { name: 'South Korea', iso: 'KR', code: '+82', flag: '🇰🇷' },
    { name: 'South Sudan', iso: 'SS', code: '+211', flag: '🇸🇸' },
    { name: 'Spain', iso: 'ES', code: '+34', flag: '🇪🇸' },
    { name: 'Sri Lanka', iso: 'LK', code: '+94', flag: '🇱🇰' },
    { name: 'Sudan', iso: 'SD', code: '+249', flag: '🇸🇩' },
    { name: 'Suriname', iso: 'SR', code: '+597', flag: '🇸🇷' },
    { name: 'Sweden', iso: 'SE', code: '+46', flag: '🇸🇪' },
    { name: 'Switzerland', iso: 'CH', code: '+41', flag: '🇨🇭' },
    { name: 'Syria', iso: 'SY', code: '+963', flag: '🇸🇾' },
    { name: 'Tajikistan', iso: 'TJ', code: '+992', flag: '🇹🇯' },
    { name: 'Tanzania', iso: 'TZ', code: '+255', flag: '🇹🇿' },
    { name: 'Thailand', iso: 'TH', code: '+66', flag: '🇹🇭' },
    { name: 'Togo', iso: 'TG', code: '+228', flag: '🇹🇬' },
    { name: 'Tonga', iso: 'TO', code: '+676', flag: '🇹🇴' },
    { name: 'Trinidad and Tobago', iso: 'TT', code: '+1', flag: '🇹🇹' },
    { name: 'Tunisia', iso: 'TN', code: '+216', flag: '🇹🇳' },
    { name: 'Turkey', iso: 'TR', code: '+90', flag: '🇹🇷' },
    { name: 'Turkmenistan', iso: 'TM', code: '+993', flag: '🇹🇲' },
    { name: 'Tuvalu', iso: 'TV', code: '+688', flag: '🇹🇻' },
    { name: 'Uganda', iso: 'UG', code: '+256', flag: '🇺🇬' },
    { name: 'Ukraine', iso: 'UA', code: '+380', flag: '🇺🇦' },
    { name: 'United Arab Emirates', iso: 'AE', code: '+971', flag: '🇦🇪' },
    { name: 'United Kingdom', iso: 'GB', code: '+44', flag: '🇬🇧' },
    { name: 'United States', iso: 'US', code: '+1', flag: '🇺🇸' },
    { name: 'Uruguay', iso: 'UY', code: '+598', flag: '🇺🇾' },
    { name: 'Uzbekistan', iso: 'UZ', code: '+998', flag: '🇺🇿' },
    { name: 'Vanuatu', iso: 'VU', code: '+678', flag: '🇻🇺' },
    { name: 'Venezuela', iso: 'VE', code: '+58', flag: '🇻🇪' },
    { name: 'Vietnam', iso: 'VN', code: '+84', flag: '🇻🇳' },
    { name: 'Yemen', iso: 'YE', code: '+967', flag: '🇾🇪' },
    { name: 'Zambia', iso: 'ZM', code: '+260', flag: '🇿🇲' },
    { name: 'Zimbabwe', iso: 'ZW', code: '+263', flag: '🇿🇼' }
];
